version: '3.8'

services:
  # PostgreSQL
  database:
    platform: linux/x86_64
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    healthcheck:
      test: [ "CMD" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    platform: linux/x86_64
    depends_on:
      - database
    restart: on-failure
    image: test_api_animals
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://database:${POSTGRESQL_DOCKER_PORT}/${POSTGRESQL_DATABASE}",
        "spring.datasource.username": "${POSTGRESQL_USER}",
        "spring.datasource.password": "${POSTGRESQL_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"